import { site } from "@/lib/site";

/**
 * The header uses a crop with the strapline band removed: at 150px wide that
 * line is illegible and reads as noise. The footer shows the whole thing.
 * Both are generated by `npm run logo`.
 */
const VARIANTS = {
  full: { src: "/logo.webp", width: 400, height: 291 },
  header: { src: "/logo-header.webp", width: 400, height: 246 },
} as const;

/**
 * The supplied logo, used as-is.
 *
 * It already contains the wordmark and the strapline, so nothing renders a
 * text lockup beside it — that would print the name twice.
 */
export function BrandLogo({
  className = "",
  width = 170,
  variant = "full",
}: {
  className?: string;
  /** Capped at the source's own width so it is never upscaled. */
  width?: number;
  variant?: keyof typeof VARIANTS;
}) {
  const art = VARIANTS[variant];
  const w = Math.min(width, art.width);
  const h = Math.round((w / art.width) * art.height);

  return (
    // Static export has no image optimiser, and the asset is already sized
    // for its slot.
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={art.src}
      alt={site.name}
      width={w}
      height={h}
      className={className}
      decoding="async"
    />
  );
}
